{{/* 운영은 sealed-secrets/external-secrets 으로 _대체_ */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "tender.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
